### PR TITLE
readme: update shields

### PR DESCRIPTION
**Pull request by umarcor**

### CODE REVIEW

**Review by mithro — CHANGES_REQUESTED** [review]
I think it would be better to not embed non-human readable base64 encoded stuff in our human readable file?

**Review by mithro — COMMENTED** [review]
These shields seem to be static? Hence, I think we just put the rendered image in the repository and link to it using ``?

**Comment by umarcor** [comment]
Unfortunately, the shields are dynamic. They show whether the site is online. See example without icon:

```
https://img.shields.io/website?up_color=10cfc9&up_message=%E2%9E%9A&url=https%3A%2F%2Ff4pga.org%2Findex.html

https://img.shields.io/website?up_color=10cfc9&up_message=%E2%9E%9A&url=https%3A%2F%2FDOESNOTEXIST.org%2Findex.html
```

**Comment by mithro** [comment]
> Unfortunately, the shields are dynamic. They show whether the site is online. See example without icon:
> 
> ```
> https://img.shields.io/website?up_color=10cfc9&up_message=%E2%9E%9A&url=https%3A%2F%2Ff4pga.org%2Findex.html
> 
> https://img.shields.io/website?up_color=10cfc9&up_message=%E2%9E%9A&url=https%3A%2F%2FDOESNOTEXIST.org%2Findex.html
> ```
> 
> 
> 
> 

I don't think the website up / down status is that useful reason for making our README's less readable.

**Comment by tmichalak** [comment]
LGTM

**Pull request merged**
